language: node_js
node_js: lts/*

sudo: required
services:
  - docker

before_install:
  - docker build -t adenijiazeez/docker-react -f Dockerfile-dev .

script:
  - docker run adenijiazeez/docker-react npm run test --coverage