# set the base image
# why alpine? Alpine Linux is a security-oriented, lightweight (5Mb) ubuntu
FROM node:alpine

# set working directory
WORKDIR /app

# copy package.json and npm.lock
# package.json to install the packages from 
# and npm.lock for a package called chokidar used for reloading

COPY package.json /app/package.json
COPY npm.lock /app/npm.lock

# install and cache dependencies
# n/b: these dependencies are installed inside docker
# it runs the command "npm" which is an equivalent of "npm add"
RUN npm

# copy folder content to docker image
COPY . .

# start the container
CMD ["npm", "start"]