# set the base image
# why alpine? Alpine Linux is a security-oriented, lightweight (5Mb) ubuntu
FROM node:alpine

# set working directory
WORKDIR /app

# copy package.json and yarn.lock
# package.json to install the packages from 
# and yarn.lock for a package called chokidar used for reloading

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

# install and cache dependencies
# n/b: these dependencies are installed inside docker
# it runs the command "yarn" which is an equivalent of "yarn add"
RUN yarn

# copy folder content to docker image
COPY . .

# start the container
CMD ["yarn", "start"]